hseq:
  root: "/local/hpatches-sequences-release"
  seq: ["v", "i"]
  kpt_n: 2048
  start_idx: 0
  suffix: '_cvpr'
eval:
  loc_model: 'pretrained/contextdesc++'
  reg_model: 'pretrained/retrieval_model'
  err_thld: 2.5
network:
  dense_desc: false
  ori_est: false
  aug: true
